/**
 * DON'T EDIT THIS FILE.
 * This file was generated by 'scripts/update-src-configs.ts' script.
 */
import type { TSESLint } from '@typescript-eslint/utils';

const config: TSESLint.Linter.Config = {
  plugins: ['es-roikoren'],
  rules: {
    'es-roikoren/no-accessor-properties': 'error',
    'es-roikoren/no-array-isarray': 'error',
    'es-roikoren/no-array-prototype-every': 'error',
    'es-roikoren/no-array-prototype-filter': 'error',
    'es-roikoren/no-array-prototype-foreach': 'error',
    'es-roikoren/no-array-prototype-indexof': 'error',
    'es-roikoren/no-array-prototype-lastindexof': 'error',
    'es-roikoren/no-array-prototype-map': 'error',
    'es-roikoren/no-array-prototype-reduce': 'error',
    'es-roikoren/no-array-prototype-reduceright': 'error',
    'es-roikoren/no-array-prototype-some': 'error',
    'es-roikoren/no-date-now': 'error',
    'es-roikoren/no-function-prototype-bind': 'error',
    'es-roikoren/no-json': 'error',
    'es-roikoren/no-keyword-properties': 'error',
    'es-roikoren/no-object-create': 'error',
    'es-roikoren/no-object-defineproperties': 'error',
    'es-roikoren/no-object-defineproperty': 'error',
    'es-roikoren/no-object-freeze': 'error',
    'es-roikoren/no-object-getownpropertydescriptor': 'error',
    'es-roikoren/no-object-getownpropertynames': 'error',
    'es-roikoren/no-object-getprototypeof': 'error',
    'es-roikoren/no-object-isextensible': 'error',
    'es-roikoren/no-object-isfrozen': 'error',
    'es-roikoren/no-object-issealed': 'error',
    'es-roikoren/no-object-keys': 'error',
    'es-roikoren/no-object-preventextensions': 'error',
    'es-roikoren/no-object-seal': 'error',
    'es-roikoren/no-string-prototype-trim': 'error',
    'es-roikoren/no-trailing-commas': 'error',
  },
};

export default config;
