/**
 * DON'T EDIT THIS FILE.
 * This file was generated by 'scripts/update-src-configs.ts' script.
 */
import type { TSESLint } from '@typescript-eslint/utils';

const config: TSESLint.Linter.Config = {
  plugins: ['es-roikoren'],
  rules: {
    'es-roikoren/no-logical-assignment-operators': 'error',
    'es-roikoren/no-numeric-separators': 'error',
    'es-roikoren/no-promise-any': 'error',
    'es-roikoren/no-string-prototype-replaceall': 'error',
    'es-roikoren/no-weakrefs': 'error',
  },
};

export default config;
