/**
 * DON'T EDIT THIS FILE.
 * This file was generated by 'scripts/update-src-configs.ts' script.
 */
import type { TSESLint } from '@typescript-eslint/utils';

const config: TSESLint.Linter.Config = {
  plugins: ['es-roikoren'],
  rules: { 'es-roikoren/no-array-prototype-includes': 'error', 'es-roikoren/no-exponential-operators': 'error' },
};

export default config;
