/**
 * DON'T EDIT THIS FILE.
 * This file was generated by 'scripts/update-src-configs.ts' script.
 */
import type { TSESLint } from '@typescript-eslint/experimental-utils';

const config: TSESLint.Linter.Config = {
  plugins: ['es-roikoren'],
  rules: {
    'es-roikoren/no-array-string-prototype-at': 'error',
    'es-roikoren/no-class-fields': 'error',
    'es-roikoren/no-class-static-block': 'error',
    'es-roikoren/no-object-hasown': 'error',
    'es-roikoren/no-private-in': 'error',
    'es-roikoren/no-regexp-d-flag': 'error',
    'es-roikoren/no-top-level-await': 'error',
  },
};

export default config;
