/**
 * DON'T EDIT THIS FILE.
 * This file was generated by 'scripts/update-src-configs.ts' script.
 */
import type { TSESLint } from '@typescript-eslint/utils';

const config: TSESLint.Linter.Config = {
  plugins: ['es-roikoren'],
  rules: {
    'es-roikoren/no-bigint': 'error',
    'es-roikoren/no-dynamic-import': 'error',
    'es-roikoren/no-export-ns-from': 'error',
    'es-roikoren/no-global-this': 'error',
    'es-roikoren/no-import-meta': 'error',
    'es-roikoren/no-nullish-coalescing-operators': 'error',
    'es-roikoren/no-optional-chaining': 'error',
    'es-roikoren/no-promise-all-settled': 'error',
    'es-roikoren/no-string-prototype-matchall': 'error',
  },
};

export default config;
