/**
 * DON'T EDIT THIS FILE.
 * This file was generated by 'scripts/update-src-configs.ts' script.
 */
import type { TSESLint } from '@typescript-eslint/experimental-utils';

const config: TSESLint.Linter.Config = {
  plugins: ['es-roikoren'],
  rules: {
    'es-roikoren/no-array-prototype-flat': 'error',
    'es-roikoren/no-json-superset': 'error',
    'es-roikoren/no-object-fromentries': 'error',
    'es-roikoren/no-optional-catch-binding': 'error',
    'es-roikoren/no-regexp-unicode-property-escapes-2019': 'error',
    'es-roikoren/no-string-prototype-trimstart-trimend': 'error',
    'es-roikoren/no-symbol-prototype-description': 'error',
  },
};

export default config;
