/**
 * DON'T EDIT THIS FILE.
 * This file was generated by 'scripts/update-src-configs.ts' script.
 */
export default {
  plugins: ['es-roikoren'],
  rules: {
    'es-roikoren/no-class-fields': 'error',
    'es-roikoren/no-class-static-block': 'error',
    'es-roikoren/no-object-hasown': 'error',
    'es-roikoren/no-regexp-d-flag': 'error',
  },
};
