/**
 * DON'T EDIT THIS FILE.
 * This file was generated by 'scripts/update-src-configs.ts' script.
 */
import type { TSESLint } from '@typescript-eslint/experimental-utils';

const config: TSESLint.Linter.Config = {
  plugins: ['es-roikoren'],
  rules: {
    'es-roikoren/no-async-iteration': 'error',
    'es-roikoren/no-malformed-template-literals': 'error',
    'es-roikoren/no-promise-prototype-finally': 'error',
    'es-roikoren/no-regexp-lookbehind-assertions': 'error',
    'es-roikoren/no-regexp-named-capture-groups': 'error',
    'es-roikoren/no-regexp-s-flag': 'error',
    'es-roikoren/no-regexp-unicode-property-escapes': 'error',
    'es-roikoren/no-rest-spread-properties': 'error',
  },
};

export default config;
