/**
 * DON'T EDIT THIS FILE.
 * This file was generated by 'scripts/update-src-configs.ts' script.
 */
import type { TSESLint } from '@typescript-eslint/experimental-utils';

const config: TSESLint.Linter.Config = {
  plugins: ['es-roikoren'],
  rules: {
    'es-roikoren/no-async-functions': 'off',
    'es-roikoren/no-async-iteration': 'off',
    'es-roikoren/no-nullish-coalescing-operators': 'off',
    'es-roikoren/no-optional-catch-binding': 'off',
    'es-roikoren/no-optional-chaining': 'off',
    'es-roikoren/no-rest-spread-properties': 'off',
    'es-roikoren/no-trailing-function-commas': 'off',
  },
};

export default config;
