name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 0 0 * * 0

concurrency:
  group: ci-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16
          cache: npm
      - name: Install Packages
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type
        run: npm run type
      - name: Codechecks
        run: npm run codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
      - name: Build
        run: npm run build

  test:
    name: Test

    strategy:
      matrix:
        eslint: [7, 8]
        node: [12, 14, 16]
        os: [ubuntu-latest]
        include:
          # On other platforms
          - eslint: 8
            node: 16
            os: windows-latest
          - eslint: 8
            node: 16
            os: macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install NPM v8
        if: matrix.node != 16
        run: npm i -g npm
      - name: Install Packages
        run: npm i
      - name: Install ESLint ${{ matrix.eslint }}
        run: npm i eslint@${{ matrix.eslint }} -D
      - name: Test
        run: npm test
      - name: Coverage
        run: npm run coverage
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
